### ISSUE TITLE
[Suggest] Add Crowdin to this project

### ISSUE THREAD

**Issue by tanjiarui15** [TaleWorlds/Documentations#19]
[Crowdin](https://github.com/marketplace/crowdin/) is one tool to get automated and continuous localization.

I think adding this app will help document translation. 
In addition, choosing open source plan is free to use
![image](https://user-images.githubusercontent.com/20656904/95644302-4fa78080-0ae8-11eb-9f49-13c35eea373b.png)

**Comment by comradekingu** [comment]
It isn't free to use, like it says. It also requires projects to be non-commercial.
Check out Weblate if you want something that isn't that.

**Comment by tanjiarui15** [comment]
> It isn't free to use, like it says. It also requires projects to be non-commercial.
> Check out Weblate if you want something that isn't that. How is TaleWorlds open source though?

You are right……I'll close this issue.
