### ISSUE TITLE
[Bug] Children Description in each index are not formatted in Zh_CN language.

### ISSUE THREAD

**Issue by WuZhuoran** [TaleWorlds/Documentations#26]
Here is the link: http://docs.modding.bannerlord.com/zh_cn/playing-sounds/
http://docs.modding.bannerlord.com/zh_cn/asset-management/

The screenshot for the first one is:
<img width="1436" alt="Screen Shot 2020-10-13 at 9 06 24 AM" src="https://user-images.githubusercontent.com/8717187/95886394-61309880-0d33-11eb-95b2-d79fe5d17f43.png">

Is there a way to write the each page's description directly? Now the description seems the be extracted from each page.

**Comment by OzgurEraslan** [comment]
creating an _index.md in each folder should override the default description (which is pulled from child folders).

**Comment by Bisstocuz** [comment]
This issue has been solved.
