### ISSUE TITLE
[Bug] Gor Error 522 when visiting the website.

### ISSUE THREAD

**Issue by WuZhuoran** [TaleWorlds/Documentations#30]
Will checkout later.

![Screen Shot 2020-10-14 at 12 13 24 PM](https://user-images.githubusercontent.com/8717187/96034633-aaa5e400-0e16-11eb-9374-87f56aee71c6.png)

**Comment by WuZhuoran** [comment]
Sovled now

**Comment by OzgurEraslan** [comment]
Yes our server was stuck in maintenance mode, should not happen again.
