### ISSUE TITLE
What is RGL?

### ISSUE THREAD

**Issue by WuZhuoran** [TaleWorlds/Documentations#44]
In a few docs such as [path.md](http://docs.modding.bannerlord.com/asset-management/asset-types/path/), it mentioned a term `RGL`.
It looks like the `Ruby Graph Library` or something. 
Refer this: https://github.com/monora/rgl and https://r-forge.r-project.org/projects/rgl/

I think this is a library that is based on `OpenGL` and Bannerlord Engine used as one of the graph library. But I am not sure the exact the meaning for this.

**Comment by OzgurEraslan** [comment]
Rgl is the name we use to refer our proprietary game engine. 
Naming has nothing to do with Ruby Graph Library, or any other library.
Abbreviations do not need an expansion or explanation, as you should just call it Rgl.
