### ISSUE TITLE
[Docs] update README

### ISSUE THREAD

**Issue by WuZhuoran** [TaleWorlds/Documentations#5]
It will be more helpful if README can contain more information for beginner.

I think a few things should be covered:
* How to run locally in both Windows and Mac/Linux.
* How to start contributing the repo.
* What is the license of the documentation here (Discussion Required).
* Contributor List.

**Comment by WuZhuoran** [comment]
Start a PR #3 for this.

**Comment by Bisstocuz** [comment]
This pull request mentioned has been merged.
