### ISSUE TITLE
Where is the original page for generating_and_loading_ui_sprite_sheets?

### ISSUE THREAD

**Issue by WuZhuoran** [TaleWorlds/Documentations#86]
I found that recently documentation added one page:
http://docs.modding.bannerlord.com/bestpractices/generating_and_loading_ui_sprite_sheets/

I want to make contribution with i18n since this page is very useful. But I did not found this page in this repo.

**Comment by Bisstocuz** [comment]
Located in Documentations/docs/content/schinese/Asset Management/generating_and_loading_ui_sprite_sheets.md.

**Comment by WuZhuoran** [comment]
> Located in Documentations/docs/content/schinese/Asset Management/generating_and_loading_ui_sprite_sheets.md.

https://github.com/TaleWorlds/Documentations/tree/master/docs/content/schinese/BestPractices
Here? I did not see that.

**Comment by WuZhuoran** [comment]
Oh. got it. https://github.com/TaleWorlds/Documentations/blob/master/docs/content/schinese/Asset%20Management/generating_and_loading_ui_sprite_sheets.md
Here... 

Thanks for that.
