### ISSUE TITLE
Website is down and images related to this repo are not loading

### ISSUE THREAD

**Issue by Servius** [TaleWorlds/Documentations#94]
Website is down and images related to this repo are not loading

**Comment by Bisstocuz** [comment]
Commonly, server is down while maintaining. And about images are not loading, could you please provide more detials?

**Comment by Servius** [comment]
The website has been down for a **very** long time, its not just simple maintenance, and theres been zero ETA on completion. 

https://github.com/TaleWorlds/Documentations/blob/master/docs/content/english/Asset%20Management/generating_and_loading_ui_sprite_sheets.md

^None of the relavent images load for this tutorial, making it very difficult to follow along.

**Comment by Bisstocuz** [comment]
> The website has been down for a **very** long time, its not just simple maintenance, and theres been zero ETA on completion.
> 
> https://github.com/TaleWorlds/Documentations/blob/master/docs/content/english/Asset%20Management/generating_and_loading_ui_sprite_sheets.md
> 
> ^None of the relavent images load for this tutorial, making it very difficult to follow along.

http://docs.modding.bannerlord.com/asset-management/generating_and_loading_ui_sprite_sheets/
Excuse me, I can visit it as normal. Please check your network environment or try to use proxy to visit it.
